#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

$a = __DIR__.'/vendor/autoload.php';
require $a;

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

exit($status);
